#cloud-config
package_update: false
package_upgrade: false
package_reboot_if_required: false

manage-resolv-conf: true
resolv_conf:
  nameservers:
    - '8.8.8.8'
    - '8.8.4.4'

users:
  - name: root
    shell: /bin/bash
    ssh-authorized-keys:
      - ${SSH_PUBLIC_KEY}

final_message: "The system is finally up, after $UPTIME seconds"