version: '3.7'

services:
  docker-host:
    labels:
      com.example.usage: "DOCKER_HOST=tcp://localhost:2378 docker info"
      com.example.ssh_import: "export SSH_PUBLIC_KEY=$$(cat ~/.ssh/id_rsa.pub)"
      com.example.option.qemu_memory: "$${QEMU_MEMORY:-'4G'}"
      com.example.option.expose_ssh: "$${EXPOSE_SSH:-5555}"
      com.example.option.expose_docker: "$${EXPOSE_DOCKER:-2378}"
    privileged: true
    cap_add:
      - ALL
    image: rafaelcalleja/docker-in-qemu
    build:
      context: .
      dockerfile: ./Dockerfile
    tty: true
    stdin_open: true
    working_dir: ${PWD}
    volumes:
      - /dev/shm:/dev/shm
      - ${VM_IMAGE:?VM image must be supplied}:/image
      - ${CLOUD_INIT:?Required CLOUD_INIT}:/cloud-init.yaml
    devices:
      - /dev/kvm:/dev/kvm
    ports:
      - 2378:${EXPOSE_DOCKER:-2378}
      - 5555:${EXPOSE_SSH:-5555}
    environment:
      - SSH_PUBLIC_KEY=${SSH_PUBLIC_KEY:?Required SSH_PUBLIC_KEY}
      - CLOUD_INIT=${CLOUD_INIT:?Required CLOUD_INIT}
      - EXPOSE_SSH=${EXPOSE_SSH:-5555}
      - EXPOSE_DOCKER=${EXPOSE_DOCKER:-2378}
