version: '3.6'

services:
  sut:
    privileged: true
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: test-1/Dockerfile
      args:
        PWD: ${PWD:?PWD Required}
    command: "/run_test.sh"
    environment:
      - BUILD_CODE
    working_dir: /src/${BUILD_CODE}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /src/${BUILD_CODE}:/src/${BUILD_CODE}
