version: '3.6'

services:
  sut:
    build:
      context: .
      dockerfile: test-1/Dockerfile
      args:
        PWD: ${PWD:?PWD Required}
    command: "/run_test.sh"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:${PWD}
      - $HOME/.docker/config.json:/root/.docker/config.json
